CREATE TABLE DEPARTMENT (
  Number INTEGER NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Location VARCHAR(255) NULL,
  PRIMARY KEY(Number)
);

CREATE TABLE PROJECT (
  Number INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DEPARTMENT_Number INTEGER NOT NULL,
  Location INTEGER UNSIGNED NULL,
  Name VARCHAR(45) NOT NULL,
  PRIMARY KEY(Number),
  FOREIGN KEY(DEPARTMENT_Number)
    REFERENCES DEPARTMENT(Number)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EMPLOYEE (
  SSN INTEGER UNSIGNED NOT NULL,
  Supervisor INTEGER UNSIGNED NOT NULL,
  DEPARTMENT_Number INTEGER NOT NULL,
  Bdate DATE NOT NULL,
  Fname VARCHAR(20) NOT NULL,
  Minit VARCHAR(3) NULL,
  Lname VARCHAR(20) NOT NULL,
  Sex VARCHAR(3) NOT NULL,
  Street VARCHAR(20) NULL,
  Num FLOAT NULL,
  Complement VARCHAR(10) NULL,
  City VARCHAR(20) NULL,
  State VARCHAR(20) NULL,
  ZipCode INTEGER UNSIGNED NULL,
  Salary FLOAT NOT NULL,
  PRIMARY KEY(SSN),
  FOREIGN KEY(DEPARTMENT_Number)
    REFERENCES DEPARTMENT(Number)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Supervisor)
    REFERENCES EMPLOYEE(SSN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DEPENDENT (
  EMPLOYEE_SSN INTEGER UNSIGNED NOT NULL,
  Fname VARCHAR(45) NOT NULL,
  Minit VARCHAR(3) NULL,
  Lname VARCHAR(20) NOT NULL,
  Sex VARCHAR(3) NOT NULL,
  BDate DATE NULL,
  Relationship VARCHAR(20) NOT NULL,
  FOREIGN KEY(EMPLOYEE_SSN)
    REFERENCES EMPLOYEE(SSN)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE Works_on (
  EMPLOYEE_SSN INTEGER UNSIGNED NOT NULL,
  PROJECT_Number INTEGER UNSIGNED NOT NULL,
  Hrs INTEGER UNSIGNED NULL,
  PRIMARY KEY(EMPLOYEE_SSN, PROJECT_Number),
  FOREIGN KEY(EMPLOYEE_SSN)
    REFERENCES EMPLOYEE(SSN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROJECT_Number)
    REFERENCES PROJECT(Number)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


